### PR TITLE
fix build by exporting eh_personality

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by nbdd0121** [comment]
This bumps MSRV to 1.75, causing nix-ld-rs to no longer compile with rustc 1.73 (comes with NixOS 23.11)

**Comment by Mic92** [comment]
Ok. Maybe use an old version for now. There are no important fixes in master beyond crate bumps.

**Comment by Mic92** [comment]
The package is also in nixpkgs now, so in the next release this won't happen again.

**Comment by nbdd0121** [comment]
> The package is also in nixpkgs now, so in the next release this won't happen again.

Good to know, thanks!

**Pull request merged**
